version: '3.8'

services:
  api:
    build:
      context: ./apps/be
      dockerfile: Dockerfile
    container_name: cart_api
    ports:
      - '3000:3000'
    env_file:
      - ./apps/be/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: cart_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cart_app
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: